name: Node CI

on:
  push

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up python ${{ matrix.python-version }}
      uses: action/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display python version
      run: python --version


