name: Node CI

on:
  push

defaults:
  run:
    shell: bash

jobs:
  build_on_windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display python version
      run: python --version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install flake8
        pip install -r requirements.txt
    - name: Cache VSTSDK archive
      id: vst-sdk-archive-cache
      uses: actions/cache@v2
      with:
        path: build/vstsdk.zip
        key: vstsdk_cache
    - name: Cache VSTSDK
      id: vst-sdk-cache
      uses: actions/cache@v2
      with:
        path: build/vstsdk
        key: uncompressed_vstsdk_cache
    - name: Build Cython module
      run: |
        python setup.py build_ext --inplace
    - name: build dist
      run: |
        python setup.py bdist_wheel
    - name: Inspecting dist contents
      run: |
        ls -la dist/
    - name: upload whl as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: whl_win_${{ matrix.python-version }}
        path: dist/*.whl


  release:
    runs-on: ubuntu-latest
    needs: [ build_on_windows ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - uses: actions/download-artifact@v2
      with:
        name: whl_win_3.7
        path: dist
    - uses: actions/download-artifact@v2
      with:
        name: whl_win_3.8
        path: dist
    - uses: actions/download-artifact@v2
      with:
        name: whl_win_3.9
        path: dist
    - name: Inspecting dist after downloading artifacts
      run: |
        ls -la dist/